import 'dart:convert';

import 'package:drift/drift.dart';

import '../../core/constants/constants.dart';
import '../local/database.dart';
import '../local/tables/sync_ops_table.dart';
import '../local/tables/transactions_table.dart';
import 'op_logger.dart';

/// 流水仓库：本地乐观写 + OpLogger 入队（Spec §3.1 / BK-P0-001）；
/// 查询/写入强制按账本过滤（Spec §4.1 / BK-T-010）
class TransactionRepository {
  TransactionRepository(this.db, {OpLogger? opLogger, this.bookId})
      : opLogger = opLogger ?? OpLogger(db);

  final AppDatabase db;
  final OpLogger opLogger;
  final String? bookId;

  static const _defaultsPrefix = 'last_defaults_';

  /// 显式账本上下文优先，否则回退本地默认分区（kDefaultBookId）
  Future<String> _bookId() async => bookId ?? kDefaultBookId;

  Future<int> createTransaction({
    required int accountId,
    int? categoryId,
    required TransactionType type,
    required int amountMinor,
    required DateTime occurredAt,
    String? note,
    bool autoGenerated = false,
    // 多币种三要素（Spec §4.5 / BK-T-014）：原币金额 + 币种 + 记账时汇率快照
    String currency = 'CNY',
    int? rateSnapshot,
  }) async {
    final currentBookId = await _bookId();
    return db.transaction(() async {
      final now = DateTime.now().toUtc();
      final remoteId = opLogger.newUuid();
      final id = await db.into(db.transactions).insert(TransactionsCompanion.insert(
            bookId: Value(currentBookId),
            remoteId: Value(remoteId),
            accountId: accountId,
            categoryId: Value(categoryId),
            type: type,
            amountMinor: amountMinor,
            currency: currency,
            rateSnapshot: Value(rateSnapshot ?? kRateScale),
            occurredAt: occurredAt,
            note: Value(note),
            autoGenerated: Value(autoGenerated),
            updatedAt: now,
          ));
      await opLogger.enqueue(
        entity: 'transaction',
        entityId: id,
        remoteId: remoteId,
        op: SyncOpCode.c,
        bookId: currentBookId,
        payload: {
          'id': id,
          'account_id': await _remoteIdOf('accounts', accountId),
          'category_id': categoryId == null ? null : await _remoteIdOf('categories', categoryId),
          'type': type.name,
          'amount_minor': amountMinor,
          'currency': currency,
          'rate_snapshot': rateSnapshot,
          'occurred_at': occurredAt.toUtc().toIso8601String(),
          'note': note,
          'auto_generated': autoGenerated,
          'updated_at': now.toIso8601String(),
        },
      );
      return id;
    });
  }

  /// 软删除 + delete op（op-log 模型，Spec §1.3；delete payload 为 null）
  Future<void> deleteTransaction(int id) async {
    await db.transaction(() async {
      final row = await (db.select(db.transactions)..where((t) => t.id.equals(id))).getSingle();
      await (db.update(db.transactions)..where((t) => t.id.equals(id)))
          .write(TransactionsCompanion(
        deletedAt: Value(DateTime.now().toUtc()),
        updatedAt: Value(DateTime.now().toUtc()),
      ));
      await opLogger.enqueue(
        entity: 'transaction',
        entityId: id,
        remoteId: row.remoteId!,
        op: SyncOpCode.d,
        bookId: await _bookId(),
      );
    });
  }

  Future<int> createTransfer({
    required int fromAccountId,
    required int toAccountId,
    required int amountMinor,
    required DateTime occurredAt,
  }) async {
    final currentBookId = await _bookId();
    return db.transaction(() async {
      final now = DateTime.now().toUtc();
      final fromRemoteId = opLogger.newUuid();
      final pairedRemoteId = opLogger.newUuid();
      final fromId = await db.into(db.transactions).insert(TransactionsCompanion.insert(
            bookId: Value(currentBookId),
            remoteId: Value(fromRemoteId),
            accountId: fromAccountId,
            type: TransactionType.transfer,
            amountMinor: -amountMinor,
            currency: 'CNY',
            occurredAt: occurredAt,
            updatedAt: now,
          ));
      final pairedId = await db.into(db.transactions).insert(TransactionsCompanion.insert(
            bookId: Value(currentBookId),
            remoteId: Value(pairedRemoteId),
            accountId: toAccountId,
            type: TransactionType.transfer,
            amountMinor: amountMinor,
            currency: 'CNY',
            occurredAt: occurredAt,
            transferId: Value(fromId),
            updatedAt: now,
          ));
      await (db.update(db.transactions)..where((t) => t.id.equals(fromId)))
          .write(TransactionsCompanion(transferId: Value(fromId)));

      final fromAccountRef = await _remoteIdOf('accounts', fromAccountId);
      final toAccountRef = await _remoteIdOf('accounts', toAccountId);
      await opLogger.enqueue(
        entity: 'transaction',
        entityId: fromId,
        remoteId: fromRemoteId,
        op: SyncOpCode.c,
        bookId: currentBookId,
        payload: {
          'id': fromId,
          'account_id': fromAccountRef,
          'transfer_id': fromRemoteId,
          'type': 'transfer',
          'amount_minor': -amountMinor,
          'currency': 'CNY',
          'occurred_at': occurredAt.toUtc().toIso8601String(),
          'updated_at': now.toIso8601String(),
        },
      );
      await opLogger.enqueue(
        entity: 'transaction',
        entityId: pairedId,
        remoteId: pairedRemoteId,
        op: SyncOpCode.c,
        bookId: currentBookId,
        payload: {
          'id': pairedId,
          'account_id': toAccountRef,
          'transfer_id': fromRemoteId,
          'type': 'transfer',
          'amount_minor': amountMinor,
          'currency': 'CNY',
          'occurred_at': occurredAt.toUtc().toIso8601String(),
          'updated_at': now.toIso8601String(),
        },
      );
      return fromId;
    });
  }

  Future<String?> _remoteIdOf(String table, int id) async {
    final sql = 'SELECT remote_id FROM $table WHERE id = ?';
    final row = await db.customSelect(sql, variables: [Variable.withInt(id)]).getSingleOrNull();
    return row?.read<String?>('remote_id');
  }

  Future<void> rememberDefaults({
    required TransactionType type,
    required int? categoryId,
    required int? accountId,
  }) async {
    final key = '$_defaultsPrefix${type.name}';
    final value = jsonEncode({'category_id': categoryId, 'account_id': accountId});
    await db.into(db.appMeta).insert(
          AppMetaCompanion.insert(key: key, value: value),
          onConflict: DoUpdate((_) => AppMetaCompanion(value: Value(value))),
        );
  }

  Future<({int? categoryId, int? accountId})?> lastDefaults(TransactionType type) async {
    final rows = await (db.select(db.appMeta)
          ..where((t) => t.key.equals('$_defaultsPrefix${type.name}')))
        .get();
    if (rows.isEmpty) return null;
    final data = jsonDecode(rows.single.value) as Map<String, dynamic>;
    return (categoryId: data['category_id'] as int?, accountId: data['account_id'] as int?);
  }

  Future<List<Transaction>> listTransactions({bool includeDeleted = false}) async {
    final currentBookId = await _bookId();
    final q = db.select(db.transactions)
      ..where((t) => t.bookId.equals(currentBookId))
      ..orderBy([(t) => OrderingTerm.desc(t.occurredAt)]);
    if (!includeDeleted) q.where((t) => t.deletedAt.isNull());
    return q.get();
  }

  /// 幂等去重查询（Spec §4.2：金额+时间+对方 已存在则跳过）
  Future<bool> findDuplicate({
    required int amountMinor,
    required DateTime occurredAt,
    String? note,
  }) async {
    final currentBookId = await _bookId();
    final start = DateTime.utc(
      occurredAt.year,
      occurredAt.month,
      occurredAt.day,
      occurredAt.hour,
      occurredAt.minute,
    );
    final end = start.add(const Duration(minutes: 1));
    final q = db.select(db.transactions)
      ..where((t) =>
          t.bookId.equals(currentBookId) &
          t.amountMinor.equals(amountMinor) &
          t.occurredAt.isBiggerOrEqualValue(start) &
          t.occurredAt.isSmallerThanValue(end) &
          (note == null ? t.note.isNull() : t.note.equals(note)) &
          t.deletedAt.isNull());
    final rows = await q.get();
    return rows.isNotEmpty;
  }
}
