import 'dart:convert';

import 'package:drift/drift.dart';

import '../local/database.dart';
import '../local/tables/sync_ops_table.dart';
import '../local/tables/transactions_table.dart';
import 'op_logger.dart';

/// 流水仓库：本地乐观写 + OpLogger 入队（Spec §3.1 / BK-P0-001）
class TransactionRepository {
  TransactionRepository(this.db, {OpLogger? opLogger}) : opLogger = opLogger ?? OpLogger(db);

  final AppDatabase db;
  final OpLogger opLogger;

  static const _defaultsPrefix = 'last_defaults_';

  Future<int> createTransaction({
    required int accountId,
    int? categoryId,
    required TransactionType type,
    required int amountMinor,
    required DateTime occurredAt,
    String? note,
    bool autoGenerated = false,
  }) async {
    return db.transaction(() async {
      final now = DateTime.now().toUtc();
      final remoteId = opLogger.newUuid();
      final id = await db.into(db.transactions).insert(TransactionsCompanion.insert(
            remoteId: Value(remoteId),
            accountId: accountId,
            categoryId: Value(categoryId),
            type: type,
            amountMinor: amountMinor,
            currency: 'CNY',
            occurredAt: occurredAt,
            note: Value(note),
            autoGenerated: Value(autoGenerated),
            updatedAt: now,
          ));
      await opLogger.enqueue(
        entity: 'transaction',
        entityId: id,
        remoteId: remoteId,
        op: SyncOpCode.c,
        payload: {
          'id': id,
          'account_id': await _remoteIdOf('accounts', accountId),
          'category_id': categoryId == null ? null : await _remoteIdOf('categories', categoryId),
          'type': type.name,
          'amount_minor': amountMinor,
          'currency': 'CNY',
          'occurred_at': occurredAt.toUtc().toIso8601String(),
          'note': note,
          'auto_generated': autoGenerated,
          'updated_at': now.toIso8601String(),
        },
      );
      return id;
    });
  }

  /// 软删除 + delete op（op-log 模型，Spec §1.3；delete payload 为 null）
  Future<void> deleteTransaction(int id) async {
    await db.transaction(() async {
      final row = await (db.select(db.transactions)..where((t) => t.id.equals(id))).getSingle();
      await (db.update(db.transactions)..where((t) => t.id.equals(id)))
          .write(TransactionsCompanion(
        deletedAt: Value(DateTime.now().toUtc()),
        updatedAt: Value(DateTime.now().toUtc()),
      ));
      await opLogger.enqueue(
        entity: 'transaction',
        entityId: id,
        remoteId: row.remoteId!,
        op: SyncOpCode.d,
      );
    });
  }

  Future<int> createTransfer({
    required int fromAccountId,
    required int toAccountId,
    required int amountMinor,
    required DateTime occurredAt,
  }) async {
    return db.transaction(() async {
      final now = DateTime.now().toUtc();
      final fromRemoteId = opLogger.newUuid();
      final pairedRemoteId = opLogger.newUuid();
      final fromId = await db.into(db.transactions).insert(TransactionsCompanion.insert(
            remoteId: Value(fromRemoteId),
            accountId: fromAccountId,
            type: TransactionType.transfer,
            amountMinor: -amountMinor,
            currency: 'CNY',
            occurredAt: occurredAt,
            updatedAt: now,
          ));
      final pairedId = await db.into(db.transactions).insert(TransactionsCompanion.insert(
            remoteId: Value(pairedRemoteId),
            accountId: toAccountId,
            type: TransactionType.transfer,
            amountMinor: amountMinor,
            currency: 'CNY',
            occurredAt: occurredAt,
            transferId: Value(fromId),
            updatedAt: now,
          ));
      await (db.update(db.transactions)..where((t) => t.id.equals(fromId)))
          .write(TransactionsCompanion(transferId: Value(fromId)));

      final fromAccountRef = await _remoteIdOf('accounts', fromAccountId);
      final toAccountRef = await _remoteIdOf('accounts', toAccountId);
      await opLogger.enqueue(
        entity: 'transaction',
        entityId: fromId,
        remoteId: fromRemoteId,
        op: SyncOpCode.c,
        payload: {
          'id': fromId,
          'account_id': fromAccountRef,
          'transfer_id': fromRemoteId,
          'type': 'transfer',
          'amount_minor': -amountMinor,
          'currency': 'CNY',
          'occurred_at': occurredAt.toUtc().toIso8601String(),
          'updated_at': now.toIso8601String(),
        },
      );
      await opLogger.enqueue(
        entity: 'transaction',
        entityId: pairedId,
        remoteId: pairedRemoteId,
        op: SyncOpCode.c,
        payload: {
          'id': pairedId,
          'account_id': toAccountRef,
          'transfer_id': fromRemoteId,
          'type': 'transfer',
          'amount_minor': amountMinor,
          'currency': 'CNY',
          'occurred_at': occurredAt.toUtc().toIso8601String(),
          'updated_at': now.toIso8601String(),
        },
      );
      return fromId;
    });
  }

  Future<String?> _remoteIdOf(String table, int id) async {
    final sql = 'SELECT remote_id FROM $table WHERE id = ?';
    final row = await db.customSelect(sql, variables: [Variable.withInt(id)]).getSingleOrNull();
    return row?.read<String?>('remote_id');
  }

  Future<void> rememberDefaults({
    required TransactionType type,
    required int? categoryId,
    required int? accountId,
  }) async {
    final key = '$_defaultsPrefix${type.name}';
    final value = jsonEncode({'category_id': categoryId, 'account_id': accountId});
    await db.into(db.appMeta).insert(
          AppMetaCompanion.insert(key: key, value: value),
          onConflict: DoUpdate((_) => AppMetaCompanion(value: Value(value))),
        );
  }

  Future<({int? categoryId, int? accountId})?> lastDefaults(TransactionType type) async {
    final rows = await (db.select(db.appMeta)
          ..where((t) => t.key.equals('$_defaultsPrefix${type.name}')))
        .get();
    if (rows.isEmpty) return null;
    final data = jsonDecode(rows.single.value) as Map<String, dynamic>;
    return (categoryId: data['category_id'] as int?, accountId: data['account_id'] as int?);
  }

  Future<List<Transaction>> listTransactions({bool includeDeleted = false}) {
    final q = db.select(db.transactions)
      ..orderBy([(t) => OrderingTerm.desc(t.occurredAt)]);
    if (!includeDeleted) q.where((t) => t.deletedAt.isNull());
    return q.get();
  }
}
