import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:bookkeep_app/data/local/database.dart';
import 'package:bookkeep_app/data/local/tables/accounts_table.dart';
import 'package:bookkeep_app/data/local/tables/transactions_table.dart';
import 'package:bookkeep_app/data/repositories/transaction_repository.dart';
import 'package:bookkeep_app/domain/services/capture_candidate.dart';
import 'package:bookkeep_app/features/auto_capture/import_service.dart';

import '../../../helpers/sqlite.dart';

CaptureCandidate candidate({
  required int amountMinor,
  String counterparty = '商户A',
  DateTime? at,
}) {
  return CaptureCandidate(
    amountMinor: amountMinor,
    occurredAt: at ?? DateTime.utc(2026, 7, 1, 10),
    counterparty: counterparty,
    type: amountMinor < 0 ? TransactionType.expense : TransactionType.income,
  );
}

void main() {
  ensureSqliteLoaded();
  late AppDatabase db;
  late TransactionRepository repo;
  late CsvImportService service;

  setUp(() async {
    db = AppDatabase(NativeDatabase.memory());
    repo = TransactionRepository(db);
    service = CsvImportService(repo);
    await db.into(db.accounts).insert(AccountsCompanion.insert(
          accountType: AccountType.cash,
          name: '钱包',
          currency: 'CNY',
          createdAt: DateTime.utc(2026, 8, 1),
        ));
  });

  tearDown(() => db.close());

  test('批内去重：相同金额+时间+对方只保留一条', () async {
    final deduped = await service.dedupe([
      candidate(amountMinor: -1000),
      candidate(amountMinor: -1000),
      candidate(amountMinor: -1000, at: DateTime.utc(2026, 7, 1, 11)),
      candidate(amountMinor: -2000),
    ]);
    expect(deduped, hasLength(3));
  });

  test('库内去重：已存在的流水不重复导入（幂等回归，Spec §4.2）', () async {
    const accountId = 1;
    await repo.createTransaction(
      accountId: accountId,
      categoryId: null,
      type: TransactionType.expense,
      amountMinor: -1000,
      occurredAt: DateTime.utc(2026, 7, 1, 10),
      note: '商户A',
      autoGenerated: true,
    );
    final deduped = await service.dedupe([
      candidate(amountMinor: -1000, counterparty: '商户A'),
      candidate(amountMinor: -1000, counterparty: '商户B'),
    ]);
    expect(deduped, hasLength(1)); // 商户A 已存在 → 跳过
    expect(deduped.single.counterparty, '商户B');
  });

  test('commit 批量入账并标记 auto_generated', () async {
    await service.commit(
      [
        candidate(amountMinor: -500),
        candidate(amountMinor: 300),
      ],
      accountId: 1,
    );
    final txs = await db.select(db.transactions).get();
    expect(txs, hasLength(2));
    expect(txs.every((t) => t.autoGenerated), isTrue);
    expect(txs.map((t) => t.amountMinor).toSet(), {-500, 300});
    expect(txs.every((t) => t.note == '商户A'), isTrue);
  });

  test('重复导入完整流程幂等（导入两次仅一条新增）', () async {
    final candidates = [
      candidate(amountMinor: -1000),
      candidate(amountMinor: -2000),
    ];
    final first = await service.dedupe(candidates);
    expect(first, hasLength(2));
    await service.commit(first, accountId: 1);

    final second = await service.dedupe(candidates);
    expect(second, isEmpty); // 全部已存在 → 无新增

    expect(await db.select(db.transactions).get(), hasLength(2));
  });

  test('500 条导入无重复（验证标准：批内去重 + 库内幂等）', () async {
    // 250 条唯一 + 250 条重复（每种唯一记录各重复一次）
    final candidates = <CaptureCandidate>[];
    for (var i = 0; i < 250; i++) {
      final c = candidate(
        amountMinor: -(i * 10 + 5),
        counterparty: '商户$i',
        at: DateTime.utc(2026, 7, (i % 28) + 1, 10 + (i % 12)),
      );
      candidates.add(c);
      candidates.add(c); // 批内重复
    }
    final deduped = await service.dedupe(candidates);
    expect(deduped, hasLength(250)); // 批内去重后恰 250 条

    await service.commit(deduped, accountId: 1);
    expect(await db.select(db.transactions).get(), hasLength(250));

    // 再次导入同一批：全部已在库 → 0 新增
    final reImport = await service.dedupe(candidates);
    expect(reImport, isEmpty);
    expect(await db.select(db.transactions).get(), hasLength(250));
  });
}
