import 'package:drift/drift.dart';

import '../../../core/constants/constants.dart';
import 'accounts_table.dart';
import 'categories_table.dart';

enum TransactionType { expense, income, transfer }

/// 流水：金额为整数最小货币单位（分），汇率快照定点数（Spec §1.2）
@TableIndex(name: 'idx_transactions_occurred_at', columns: {#occurredAt})
class Transactions extends Table {
  IntColumn get id => integer().autoIncrement()();
  /// 跨设备实体身份（uuid v4，同步域 entity_id）
  TextColumn get remoteId => text().named('remote_id').nullable()();
  IntColumn get accountId => integer().named('account_id').references(Accounts, #id)();
  IntColumn get categoryId => integer().named('category_id').nullable().references(Categories, #id)();
  TextColumn get type => textEnum<TransactionType>()();
  IntColumn get amountMinor => integer().named('amount_minor')();
  TextColumn get currency => text()();
  IntColumn get rateSnapshot => integer().named('rate_snapshot').withDefault(const Constant(kRateScale))();
  TextColumn get note => text().nullable()();
  DateTimeColumn get occurredAt => dateTime().named('occurred_at')();
  IntColumn get transferId => integer().named('transfer_id').nullable()();
  BoolColumn get autoGenerated => boolean().named('auto_generated').withDefault(const Constant(false))();
  DateTimeColumn get updatedAt => dateTime().named('updated_at')();
  DateTimeColumn get deletedAt => dateTime().named('deleted_at').nullable()();
}
