import 'package:flutter_test/flutter_test.dart';

import 'package:bookkeep_app/data/local/database.dart';
import 'package:bookkeep_app/data/local/tables/transactions_table.dart';
import 'package:bookkeep_app/features/bills/bills_grouping.dart';

import '../../../helpers/fixtures.dart';

Transaction t(
  int id,
  DateTime at, {
  TransactionType type = TransactionType.expense,
  int amountMinor = -100,
}) {
  return Transaction(
    id: id,
    bookId: testBookId,
    accountId: 1,
    categoryId: null,
    type: type,
    amountMinor: amountMinor,
    currency: 'CNY',
    rateSnapshot: 1000000,
    note: null,
    occurredAt: at,
    transferId: null,
    autoGenerated: false,
    updatedAt: at,
    deletedAt: null,
  );
}

/// 账单按天分组（纯函数）：本地日分组、天降序、收支合计排除转账
void main() {
  test('groups by local day desc and sums expense/income excluding transfers', () {
    final txns = [
      t(1, DateTime(2026, 8, 3, 10, 30), amountMinor: -1000),
      t(2, DateTime(2026, 8, 3, 9, 0), type: TransactionType.income, amountMinor: 2000),
      t(3, DateTime(2026, 8, 3, 8, 0), type: TransactionType.transfer, amountMinor: -300),
      t(4, DateTime(2026, 8, 3, 8, 1), type: TransactionType.transfer, amountMinor: 300),
      t(5, DateTime(2026, 8, 1, 12, 0), amountMinor: -500),
    ];

    final days = groupBillsByDay(txns);

    expect(days, hasLength(2));
    expect(days[0].day, DateTime(2026, 8, 3));
    expect(days[1].day, DateTime(2026, 8, 1));
    // 转账两条腿不进收支合计
    expect(days[0].expenseMinor, 1000);
    expect(days[0].incomeMinor, 2000);
    // 天内保持输入顺序（occurredAt 倒序）
    expect(days[0].items.map((x) => x.id).toList(), [1, 2, 3, 4]);
    expect(days[1].expenseMinor, 500);
    expect(days[1].incomeMinor, 0);
  });

  test('single day aggregates all legs', () {
    final days = groupBillsByDay([
      t(1, DateTime(2026, 8, 5, 9, 0), amountMinor: -100),
      t(2, DateTime(2026, 8, 5, 9, 0), type: TransactionType.income, amountMinor: 100),
    ]);

    expect(days, hasLength(1));
    expect(days.single.expenseMinor, 100);
    expect(days.single.incomeMinor, 100);
  });

  test('empty input yields empty days', () {
    expect(groupBillsByDay(const []), isEmpty);
  });
}
