import '../../data/repositories/transaction_repository.dart';
import '../../domain/services/capture_candidate.dart';
import 'csv_import/csv_parsers.dart';

/// CSV 导入服务（Spec §4.2 / BK-T-011）：
/// 解析 → 批内去重 → 与库内流水去重（金额+时间+对方）→ 候选经确认页入账。
class CsvImportService {
  CsvImportService(this._txRepo);

  final TransactionRepository _txRepo;

  static final parsers = <CsvTransactionParser>[AlipayCsvParser(), WechatCsvParser()];

  /// 按渠道解析（自动识别支付宝/微信格式）
  List<CaptureCandidate> parse(String csv, {String? source}) {
    for (final parser in parsers) {
      if (source != null && parser.name != source) continue;
      return parser.parse(csv);
    }
    return const [];
  }

  /// 批内去重 + 库内去重（幂等：重复导入不产生重复流水，Spec §4.2）
  Future<List<CaptureCandidate>> dedupe(List<CaptureCandidate> candidates) async {
    final seen = <String>{};
    final result = <CaptureCandidate>[];
    for (final c in candidates) {
      final key = c.dedupKey();
      if (!seen.add(key)) continue;
      if (await _txRepo.findDuplicate(
        amountMinor: c.amountMinor,
        occurredAt: c.occurredAt,
        note: c.counterparty,
      )) {
        continue;
      }
      result.add(c);
    }
    return result;
  }

  /// 批量入账（确认页调用；auto_generated 标记可追溯/撤销，Spec §4.2）
  Future<int> commit(
    List<CaptureCandidate> candidates, {
    required int accountId,
    int? Function(CaptureCandidate)? categoryResolver,
  }) async {
    var saved = 0;
    for (final c in candidates) {
      final categoryId = categoryResolver?.call(c);
      await _txRepo.createTransaction(
        accountId: accountId,
        categoryId: categoryId,
        type: c.type,
        amountMinor: c.amountMinor,
        occurredAt: c.occurredAt,
        note: c.counterparty.isEmpty ? null : c.counterparty,
        autoGenerated: true,
      );
      saved++;
    }
    return saved;
  }
}
