import 'package:drift/drift.dart';

import '../../data/local/database.dart';
import '../../data/local/tables/transactions_table.dart';
import '../../data/repositories/transaction_repository.dart';
import 'anchor_resolver.dart';
import 'recurring_engine.dart';

/// 周期记账执行（Spec §4.4 / BK-T-013）：
/// 启动/手动补跑：自 next_due 生成全部到期流水（auto_generated 标记），
/// 幂等：next_due 生成后前移，(rule_id, due_date) 天然不重复。
class RecurringService {
  RecurringService(this.db, {TransactionRepository? txRepo})
      : _txRepo = txRepo ?? TransactionRepository(db);

  final AppDatabase db;
  final TransactionRepository _txRepo;

  /// 执行单条规则补跑；返回本次生成的流水数
  Future<int> runRule(RecurringRule rule, {DateTime? now}) async {
    final current = now ?? DateTime.now();
    final spec = RecurringRuleSpec(
      frequency: _frequency(rule.frequency),
      interval: rule.interval,
      anchorType: _anchor(rule.anchorType),
      anchorDay: rule.anchorDay,
      startDate: rule.startDate,
      endDate: rule.endDate,
    );
    const engine = RecurringEngine();
    final dueDates = engine.catchUp(spec, rule.nextDue, current);

    var generated = 0;
    for (final due in dueDates) {
      // 幂等去重：next_due 之前未生成过（下次执行从新 next_due 起算）
      final occurredAt = DateTime(
        due.year,
        due.month,
        due.day,
        rule.timeOfDay ~/ 60,
        rule.timeOfDay % 60,
      );
      await _txRepo.createTransaction(
        accountId: rule.accountId,
        categoryId: rule.categoryId,
        type: TransactionType.expense,
        amountMinor: -rule.amountMinor,
        occurredAt: occurredAt,
        note: '周期记账',
        autoGenerated: true,
      );
      generated++;
    }
    if (dueDates.isNotEmpty) {
      final newNextDue = dueDates.last.add(const Duration(days: 1));
      await (db.update(db.recurringRules)..where((t) => t.id.equals(rule.id)))
          .write(RecurringRulesCompanion(nextDue: Value(newNextDue)));
    }
    return generated;
  }

  /// 全部规则补跑（App 启动调用）；返回生成总数
  Future<int> runAll({DateTime? now}) async {
    final rules = await (db.select(db.recurringRules)).get();
    var total = 0;
    for (final rule in rules) {
      total += await runRule(rule, now: now);
    }
    return total;
  }

  /// 等额分期计划：建计划 + 排期（末笔补差，合计 = 总额）
  Future<int> createInstallmentPlan({
    required String name,
    required int totalMinor,
    required int periods,
    required DateTime startDate,
    required int linkedAccountId,
    String bookId = '',
  }) async {
    final planId = await db.into(db.installmentPlans).insert(
          InstallmentPlansCompanion.insert(
            bookId: Value(bookId),
            name: name,
            totalMinor: totalMinor,
            periods: periods,
            startDate: startDate,
            linkedAccountId: linkedAccountId,
            createdAt: DateTime.now().toUtc(),
          ),
        );
    final amounts = const InstallmentCalculator().schedule(totalMinor, periods);
    for (var i = 0; i < amounts.length; i++) {
      final due = DateTime(
        startDate.year,
        startDate.month + i,
        startDate.day,
      );
      await db.into(db.installmentSchedules).insert(
            InstallmentSchedulesCompanion.insert(
              planId: planId,
              dueDate: due,
              amountMinor: amounts[i],
            ),
            onConflict: DoNothing(),
          );
    }
    return planId;
  }

  /// 到期分期 → 生成支出流水（auto_generated）；幂等：已生成过则跳过
  Future<int> runInstallmentDues({DateTime? now}) async {
    final current = now ?? DateTime.now();
    final dues = await (db.select(db.installmentSchedules)
          ..where((t) => t.dueDate.isSmallerOrEqualValue(current)))
        .get();
    var generated = 0;
    for (final due in dues) {
      final plan = await (db.select(db.installmentPlans)
            ..where((t) => t.id.equals(due.planId)))
          .getSingleOrNull();
      if (plan == null) continue;
      final exists = await (db.select(db.transactions)
            ..where((t) =>
                t.autoGenerated.equals(true) &
                t.amountMinor.equals(-due.amountMinor) &
                t.occurredAt.equals(due.dueDate) &
                t.note.equals(plan.name)))
          .get();
      if (exists.isNotEmpty) continue;
      await _txRepo.createTransaction(
        accountId: plan.linkedAccountId,
        categoryId: null,
        type: TransactionType.expense,
        amountMinor: -due.amountMinor,
        occurredAt: due.dueDate,
        note: plan.name,
        autoGenerated: true,
      );
      generated++;
    }
    return generated;
  }

  RecurringFrequency _frequency(String name) =>
      RecurringFrequency.values.firstWhere((f) => f.name == name, orElse: () => RecurringFrequency.month);

  AnchorType _anchor(String name) =>
      AnchorType.values.firstWhere((a) => a.name == name, orElse: () => AnchorType.start);
}
