import 'package:drift/drift.dart';

import '../../data/local/database.dart';
import '../../data/local/tables/transactions_table.dart';
import '../../data/repositories/transaction_repository.dart';
import 'anchor_resolver.dart';
import 'recurring_engine.dart';

/// 周期记账执行（Spec §4.4 / BK-T-013）：
/// 启动/手动补跑：自 next_due 生成全部到期流水（auto_generated 标记），
/// 幂等：next_due 生成后前移，(rule_id, due_date) 天然不重复。
class RecurringService {
  RecurringService(this.db, {required String bookId, TransactionRepository? txRepo})
      : _txRepo = txRepo ?? TransactionRepository(db, bookId: bookId);

  final AppDatabase db;
  final TransactionRepository _txRepo;

  /// 执行单条规则补跑；返回本次生成的流水数
  Future<int> runRule(RecurringRule rule, {DateTime? now}) async {
    final current = now ?? DateTime.now();
    final spec = RecurringRuleSpec(
      frequency: _frequency(rule.frequency),
      interval: rule.interval,
      anchorType: _anchor(rule.anchorType),
      anchorDay: rule.anchorDay,
      startDate: rule.startDate,
      endDate: rule.endDate,
    );
    const engine = RecurringEngine();
    final dueDates = engine.catchUp(spec, rule.nextDue, current);

    // 审查 F-7：周期收入规则生成收入流水（正金额）
    final isIncome = rule.type == 'income';
    var generated = 0;
    for (final due in dueDates) {
      // 幂等去重：next_due 之前未生成过（下次执行从新 next_due 起算）
      final occurredAt = DateTime(
        due.year,
        due.month,
        due.day,
        rule.timeOfDay ~/ 60,
        rule.timeOfDay % 60,
      );
      await _txRepo.createTransaction(
        accountId: rule.accountId,
        categoryId: rule.categoryId,
        type: isIncome ? TransactionType.income : TransactionType.expense,
        amountMinor: isIncome ? rule.amountMinor : -rule.amountMinor,
        occurredAt: occurredAt,
        note: '周期记账',
        autoGenerated: true,
      );
      generated++;
    }
    if (dueDates.isNotEmpty) {
      final newNextDue = dueDates.last.add(const Duration(days: 1));
      await (db.update(db.recurringRules)..where((t) => t.id.equals(rule.id)))
          .write(RecurringRulesCompanion(nextDue: Value(newNextDue)));
    }
    return generated;
  }

  /// 全部规则补跑（App 启动调用）；可按账本过滤；返回生成总数
  Future<int> runAll({DateTime? now, String? bookId}) async {
    final query = db.select(db.recurringRules);
    if (bookId != null) {
      query.where((t) => t.bookId.equals(bookId));
    }
    final rules = await query.get();
    var total = 0;
    for (final rule in rules) {
      total += await runRule(rule, now: now);
    }
    return total;
  }

  /// 编辑规则（BK-DOC-26 需求5）：写回频率/锚点/收支类型/金额/账户，
  /// 并以「严格晚于当前时刻的第一个到期日」重算 nextDue——不回溯补跑，
  /// 避免锚点变更意外生成历史流水。
  Future<void> updateRecurringRule(
    int id, {
    required RecurringFrequency frequency,
    required AnchorType anchorType,
    required int anchorDay,
    required String type,
    required int amountMinor,
    required int accountId,
    int? categoryId,
    DateTime? now,
  }) async {
    final current = now ?? DateTime.now();
    final rule = await (db.select(db.recurringRules)
          ..where((t) => t.id.equals(id)))
        .getSingle();
    final spec = RecurringRuleSpec(
      frequency: frequency,
      interval: rule.interval,
      anchorType: anchorType,
      anchorDay: anchorDay,
      startDate: rule.startDate,
      endDate: rule.endDate,
    );
    final nextDue = const RecurringEngine().firstDueAfter(spec, current) ?? current;
    await (db.update(db.recurringRules)..where((t) => t.id.equals(id))).write(
      RecurringRulesCompanion(
        frequency: Value(frequency.name),
        anchorType: Value(anchorType.name),
        anchorDay: Value(anchorDay),
        type: Value(type),
        amountMinor: Value(amountMinor),
        accountId: Value(accountId),
        // 编辑界面不管理分类：未显式指定时保留原值
        categoryId: Value(categoryId ?? rule.categoryId),
        nextDue: Value(nextDue),
        updatedAt: Value(DateTime.now().toUtc()),
      ),
    );
  }

  /// 删除规则（BK-DOC-26 需求5）：仅移除规则本身；已自动生成的历史
  /// 流水保留（Spec §2.5 AC5-4）。
  Future<void> deleteRecurringRule(int id) async {
    await (db.delete(db.recurringRules)..where((t) => t.id.equals(id))).go();
  }

  /// 等额分期计划：建计划 + 排期（末笔补差，合计 = 总额）
  Future<int> createInstallmentPlan({
    required String name,
    required int totalMinor,
    required int periods,
    required DateTime startDate,
    required int linkedAccountId,
    String bookId = '',
  }) async {
    final planId = await db.into(db.installmentPlans).insert(
          InstallmentPlansCompanion.insert(
            bookId: bookId,
            name: name,
            totalMinor: totalMinor,
            periods: periods,
            startDate: startDate,
            linkedAccountId: linkedAccountId,
            createdAt: DateTime.now().toUtc(),
          ),
        );
    final amounts = const InstallmentCalculator().schedule(totalMinor, periods);
    for (var i = 0; i < amounts.length; i++) {
      // 审查 L-6：月末回退（1 月 31 日 → 2 月 28/29 日，无 3 月 3 日漂移）
      final due = AnchorResolver.monthOffset(startDate, i);
      await db.into(db.installmentSchedules).insert(
            InstallmentSchedulesCompanion.insert(
              planId: planId,
              dueDate: due,
              amountMinor: amounts[i],
            ),
            onConflict: DoNothing(),
          );
    }
    return planId;
  }

  /// 到期分期 → 生成支出流水（auto_generated）；幂等：已生成过则跳过；
  /// bookId 非空时仅处理该账本的分期计划（审查 B-3 同源问题：跨账本规则不得写入他账本）
  Future<int> runInstallmentDues({DateTime? now, String? bookId}) async {
    final current = now ?? DateTime.now();
    final planIds = bookId == null
        ? null
        : (await (db.select(db.installmentPlans)..where((t) => t.bookId.equals(bookId))).get())
            .map((p) => p.id)
            .toList();
    if (bookId != null && planIds!.isEmpty) return 0;
    final query = db.select(db.installmentSchedules)
      ..where((t) => t.dueDate.isSmallerOrEqualValue(current));
    if (planIds != null) query.where((t) => t.planId.isIn(planIds));
    final dues = await query.get();
    var generated = 0;
    for (final due in dues) {
      final plan = await (db.select(db.installmentPlans)
            ..where((t) => t.id.equals(due.planId)))
          .getSingleOrNull();
      if (plan == null) continue;
      final exists = await (db.select(db.transactions)
            ..where((t) =>
                t.autoGenerated.equals(true) &
                t.amountMinor.equals(-due.amountMinor) &
                t.occurredAt.equals(due.dueDate) &
                t.note.equals(plan.name)))
          .get();
      if (exists.isNotEmpty) continue;
      await _txRepo.createTransaction(
        accountId: plan.linkedAccountId,
        categoryId: null,
        type: TransactionType.expense,
        amountMinor: -due.amountMinor,
        occurredAt: due.dueDate,
        note: plan.name,
        autoGenerated: true,
      );
      generated++;
    }
    return generated;
  }

  RecurringFrequency _frequency(String name) =>
      RecurringFrequency.values.firstWhere((f) => f.name == name, orElse: () => RecurringFrequency.month);

  AnchorType _anchor(String name) =>
      AnchorType.values.firstWhere((a) => a.name == name, orElse: () => AnchorType.start);
}
