import 'package:bookkeep_app/data/local/database.dart';
import 'package:bookkeep_app/data/local/tables/accounts_table.dart';
import 'package:bookkeep_app/data/local/tables/categories_table.dart';
import 'package:bookkeep_app/data/local/tables/transactions_table.dart';

Account account(int id, String name, int initialBalance,
    {AccountType type = AccountType.cash, String currency = 'CNY'}) {
  return Account(
    id: id,
    accountType: type,
    name: name,
    currency: currency,
    initialBalance: initialBalance,
    archived: false,
    createdAt: DateTime.utc(2026, 8, 1),
  );
}

Category category({
  required int id,
  required String name,
  required String icon,
  required int color,
  int? parentId,
  bool isSystem = false,
  DateTime? deletedAt,
  CategoryKind kind = CategoryKind.expense,
  int sortOrder = 0,
}) {
  return Category(
    id: id,
    parentId: parentId,
    name: name,
    icon: icon,
    color: color,
    kind: kind,
    isSystem: isSystem,
    sortOrder: sortOrder,
    deletedAt: deletedAt,
    updatedAt: DateTime.utc(2026, 8, 1),
  );
}

Transaction txn({
  required int accountId,
  required int amountMinor,
  int? categoryId,
  int? transferId,
  DateTime? deletedAt,
  TransactionType type = TransactionType.expense,
  int id = 1,
}) {
  return Transaction(
    id: id,
    accountId: accountId,
    categoryId: categoryId,
    type: type,
    amountMinor: amountMinor,
    currency: 'CNY',
    rateSnapshot: 1000000,
    note: null,
    occurredAt: DateTime.utc(2026, 8, 1),
    transferId: transferId,
    autoGenerated: false,
    updatedAt: DateTime.utc(2026, 8, 1),
    deletedAt: deletedAt,
  );
}
