import 'package:drift/native.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:bookkeep_app/data/local/database.dart';
import 'package:bookkeep_app/data/local/database_provider.dart';
import 'package:bookkeep_app/data/local/tables/accounts_table.dart';
import 'package:bookkeep_app/data/local/tables/transactions_table.dart';
import 'package:bookkeep_app/data/repositories/account_repository.dart';
import 'package:bookkeep_app/domain/services/capture_candidate.dart';
import 'package:bookkeep_app/features/auto_capture/capture_confirm_page.dart';
import 'package:bookkeep_app/features/books/books_providers.dart';

import '../helpers/fixtures.dart';

void main() {
  final candidates = [
    CaptureCandidate(
      amountMinor: -2500,
      occurredAt: DateTime(2026, 8, 1, 12, 30),
      counterparty: '星巴克',
      type: TransactionType.expense,
      categoryName: '午餐',
    ),
    CaptureCandidate(
      amountMinor: 10000,
      occurredAt: DateTime(2026, 8, 2, 9, 0),
      counterparty: '工资入账',
      type: TransactionType.income,
    ),
  ];

  Widget harness(AppDatabase db, List<CaptureCandidate> cands) {
    return ProviderScope(
      overrides: [
        databaseProvider.overrideWithValue(db),
        currentBookIdProvider.overrideWith((ref) => testBookId),
      ],
      child: MaterialApp(
        home: Builder(
          builder: (context) => Scaffold(
            body: Center(
              child: ElevatedButton(
                onPressed: () => CaptureConfirmPage.show(
                  context,
                  candidates: cands,
                  categoryNameFor: (c) => c.categoryName,
                  source: 'sms',
                ),
                child: const Text('打开确认页'),
              ),
            ),
          ),
        ),
      ),
    );
  }

  testWidgets('渲染候选明细：金额/对方/分类/收支方向图标', (tester) async {
    final db = AppDatabase(NativeDatabase.memory());
    addTearDown(db.close);
    await AccountRepository(db, bookId: testBookId).createAccount(name: '钱包', type: AccountType.cash);

    await tester.pumpWidget(harness(db, candidates));
    await tester.tap(find.text('打开确认页'));
    await tester.pumpAndSettle();

    expect(find.text('确认入账（2 笔）'), findsOneWidget);
    expect(find.textContaining('星巴克'), findsOneWidget);
    expect(find.textContaining('-¥25.00'), findsOneWidget);
    expect(find.textContaining('工资入账'), findsOneWidget);
    expect(find.textContaining('+¥100.00'), findsOneWidget);
    expect(find.textContaining('分类：午餐'), findsOneWidget);
    expect(find.byIcon(Icons.arrow_upward), findsOneWidget); // 支出
    expect(find.byIcon(Icons.arrow_downward), findsOneWidget); // 收入
  });

  testWidgets('点全部入账写入数据库并出现成功反馈', (tester) async {
    final db = AppDatabase(NativeDatabase.memory());
    addTearDown(db.close);
    final accountId =
        await AccountRepository(db, bookId: testBookId).createAccount(name: '工资卡', type: AccountType.cash);

    await tester.pumpWidget(harness(db, candidates));
    await tester.tap(find.text('打开确认页'));
    await tester.pumpAndSettle();

    await tester.tap(find.text('全部入账'));
    await tester.pumpAndSettle();

    expect(find.text('已入账 2 笔（可在明细中追溯/撤销）'), findsOneWidget);
    final rows = await db.select(db.transactions).get();
    expect(rows, hasLength(2));
    expect(rows.map((t) => t.amountMinor), containsAll([-2500, 10000]));
    expect(rows.every((t) => t.accountId == accountId), isTrue);
    expect(rows.every((t) => t.autoGenerated), isTrue);
  });

  testWidgets('无账户时提示先选择账户且不入库', (tester) async {
    final db = AppDatabase(NativeDatabase.memory());
    addTearDown(db.close);

    await tester.pumpWidget(harness(db, candidates));
    await tester.tap(find.text('打开确认页'));
    await tester.pumpAndSettle();

    await tester.tap(find.text('全部入账'));
    await tester.pumpAndSettle();

    expect(find.text('请先选择账户'), findsOneWidget);
    expect(await db.select(db.transactions).get(), isEmpty);
  });

  testWidgets('返回取消不入库', (tester) async {
    final db = AppDatabase(NativeDatabase.memory());
    addTearDown(db.close);
    await AccountRepository(db, bookId: testBookId).createAccount(name: '钱包', type: AccountType.cash);

    await tester.pumpWidget(harness(db, candidates));
    await tester.tap(find.text('打开确认页'));
    await tester.pumpAndSettle();

    await tester.tap(find.byType(BackButton));
    await tester.pumpAndSettle();

    expect(find.text('确认入账（2 笔）'), findsNothing);
    expect(await db.select(db.transactions).get(), isEmpty);
  });
}
