import 'package:drift/drift.dart' hide isNotNull;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:bookkeep_app/data/local/database.dart';
import 'package:bookkeep_app/data/local/tables/accounts_table.dart';
import 'package:bookkeep_app/features/recurring/recurring_service.dart';

import '../../../helpers/sqlite.dart';

void main() {
  ensureSqliteLoaded();
  late AppDatabase db;
  late RecurringService service;

  setUp(() async {
    db = AppDatabase(NativeDatabase.memory());
    service = RecurringService(db);
    await db.into(db.accounts).insert(AccountsCompanion.insert(
          accountType: AccountType.cash,
          name: '钱包',
          currency: 'CNY',
          createdAt: DateTime.utc(2026, 8, 1),
        ));
  });

  tearDown(() => db.close());

  Future<int> addRule({
    required String frequency,
    required String anchorType,
    int anchorDay = 1,
    required DateTime nextDue,
    required DateTime startDate,
    DateTime? endDate,
    int amountMinor = 10000,
    int timeOfDay = 9 * 60,
  }) async {
    return db.into(db.recurringRules).insert(RecurringRulesCompanion.insert(
          frequency: frequency,
          anchorType: anchorType,
          anchorDay: Value(anchorDay),
          amountMinor: amountMinor,
          accountId: 1,
          categoryId: const Value(null),
          nextDue: nextDue,
          startDate: startDate,
          endDate: Value(endDate),
          timeOfDay: Value(timeOfDay),
          updatedAt: DateTime.now().toUtc(),
        ));
  }

  test('月度规则补跑：mock clock 跨月生成，且幂等（30 天未开补齐无重复）', () async {
    await addRule(
      frequency: 'month',
      anchorType: 'start',
      nextDue: DateTime(2026, 6, 1),
      startDate: DateTime(2026, 6, 1),
    );

    // 模拟 30 天未开：6 月 1 日 → 7 月 1 日
    final count = await service.runRule(
      (await db.select(db.recurringRules).getSingle()),
      now: DateTime(2026, 7, 2),
    );
    expect(count, 2); // 6/1 + 7/1

    // 再次执行：无新增（幂等）
    final again = await service.runRule(
      (await db.select(db.recurringRules).getSingle()),
      now: DateTime(2026, 7, 2),
    );
    expect(again, 0);

    final txs = await db.select(db.transactions).get();
    expect(txs, hasLength(2));
    expect(txs.every((t) => t.autoGenerated), isTrue);
    expect(txs.map((t) => t.occurredAt.day).toSet(), {1});
    await db.close();
  });

  test('季度规则补跑：跨年生成正确且入账时刻 = time_of_day', () async {
    await addRule(
      frequency: 'quarter',
      anchorType: 'start',
      nextDue: DateTime(2026, 10, 1),
      startDate: DateTime(2026, 10, 1),
      timeOfDay: 9 * 60 + 30,
    );
    final count = await service.runRule(
      (await db.select(db.recurringRules).getSingle()),
      now: DateTime(2027, 4, 2),
    );
    expect(count, 3); // 2026-10-01, 2027-01-01, 2027-04-01

    final txs = await db.select(db.transactions).get();
    expect(txs, hasLength(3));
    expect(txs.map((t) => t.occurredAt.toIso8601String().substring(0, 10)).toSet(), {
      '2026-10-01',
      '2027-01-01',
      '2027-04-01',
    });
    expect(txs.every((t) => t.occurredAt.hour == 9 && t.occurredAt.minute == 30), isTrue);
    await db.close();
  });

  test('runAll 补跑全部规则且不重复', () async {
    await addRule(
      frequency: 'month',
      anchorType: 'start',
      nextDue: DateTime(2026, 7, 1),
      startDate: DateTime(2026, 7, 1),
    );
    await addRule(
      frequency: 'week',
      anchorType: 'custom',
      anchorDay: 1,
      nextDue: DateTime(2026, 8, 3),
      startDate: DateTime(2026, 8, 3),
    );
    final first = await service.runAll(now: DateTime(2026, 8, 17));
    expect(first, 5); // 月 2 条（7/1+8/1）+ 周 3 条（8/3+8/10+8/17）
    final second = await service.runAll(now: DateTime(2026, 8, 17));
    expect(second, 0);
    expect(await db.select(db.transactions).get(), hasLength(5));
    await db.close();
  });

  test('分期计划：等额排期合计 = 总额；到期生成流水幂等', () async {
    await service.createInstallmentPlan(
      name: 'iPhone 分期',
      totalMinor: 10001,
      periods: 3,
      startDate: DateTime(2026, 8, 1),
      linkedAccountId: 1,
    );
    final schedules = await db.select(db.installmentSchedules).get();
    expect(schedules, hasLength(3));
    expect(schedules.map((s) => s.amountMinor).reduce((a, b) => a + b), 10001);

    // 前两期到期 → 生成 2 笔
    final generated = await service.runInstallmentDues(now: DateTime(2026, 9, 15));
    expect(generated, 2);
    // 幂等：再次执行无新增
    expect(await service.runInstallmentDues(now: DateTime(2026, 9, 15)), 0);

    final txs = await db.select(db.transactions).get();
    expect(txs, hasLength(2));
    expect(txs.every((t) => t.autoGenerated && t.note == 'iPhone 分期'), isTrue);
    await db.close();
  });
}
